version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  flask_app:
    build: .
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
